// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2xEEIcrMioRBvNmLan_c7PPRlUXds1U',
    appId: '1:21486570168:web:35b938d0a8bd794b23824d',
    messagingSenderId: '21486570168',
    projectId: 'projeto-login-flutter',
    authDomain: 'projeto-login-flutter.firebaseapp.com',
    storageBucket: 'projeto-login-flutter.appspot.com',
    measurementId: 'G-B2112WT0X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMg7U28lQ1Y7-4VJy8GYYLf-hdwqlgElU',
    appId: '1:21486570168:android:a6d6ab37b275352223824d',
    messagingSenderId: '21486570168',
    projectId: 'projeto-login-flutter',
    storageBucket: 'projeto-login-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRQjkRLtjdrMAjq3CzAmedLDtgdN9nAQ',
    appId: '1:21486570168:ios:382b3d0801245c3623824d',
    messagingSenderId: '21486570168',
    projectId: 'projeto-login-flutter',
    storageBucket: 'projeto-login-flutter.appspot.com',
    iosClientId: '21486570168-4681g9ltu60qm6ggnjnk9uv1e6sga93h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterAnimacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRQjkRLtjdrMAjq3CzAmedLDtgdN9nAQ',
    appId: '1:21486570168:ios:382b3d0801245c3623824d',
    messagingSenderId: '21486570168',
    projectId: 'projeto-login-flutter',
    storageBucket: 'projeto-login-flutter.appspot.com',
    iosClientId: '21486570168-4681g9ltu60qm6ggnjnk9uv1e6sga93h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterAnimacao',
  );
}
